{{- if and .Values.roles.create .Values.serviceAccount.create -}}
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "grpc-person-client.serviceRoleName" . }}-reader
  labels:
    {{- include "grpc-person-client.labels" . | nindent 4 }}
  {{- with .Values.roles.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "grpc-person-client.serviceRoleName" . }}-reader-binding
  labels:
    {{- include "grpc-person-client.labels" . | nindent 4 }}
  {{- with .Values.roles.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
subjects:
- kind: ServiceAccount
  name: {{ include "grpc-person-client.serviceAccountName" . }}
  apiGroup: ""
roleRef:
  kind: Role
  name: {{ include "grpc-person-client.serviceRoleName" . }}-reader
  apiGroup: ""

{{- end}}
