spring:
  application:
    name: rsocket-person-server
  #main:
  #  cloud-platform: kubernetes
  rsocket:
    server:
      port: 9080
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  metrics:
    export:
      prometheus:
        enabled: true
