spring:
  application:
    name: flux-person-server
  #main:
  #  cloud-platform: kubernetes  
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
  metrics:
    export:
      prometheus:
        enabled: true
