apiVersion: v1
kind: Service
metadata:
  name: {{ include "rsocket-person-server.fullname" . }}
  labels:
    {{- include "rsocket-person-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9080
      targetPort: rsocket
      protocol: TCP
      name: rsocket
  selector:
    {{- include "rsocket-person-server.selectorLabels" . | nindent 4 }}
