apiVersion: v1
kind: Service
metadata:
  name: {{ include "grpc-person-server.fullname" . }}
  labels:
    {{- include "grpc-person-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 6565
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "grpc-person-server.selectorLabels" . | nindent 4 }}
